# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CICD

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        version: [14, 16, 18]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm i -g pm2
    - run: npm run build --if-present
    
    
						
      
